{
 "title": "K8s / Custom / DevOps",
 "time": { "from": "now/M", "to": "now" },
 "panels": [
  { "title": "SOURCE builds statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful Source builds this week",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "openshift_build_total{phase=\"Complete\",strategy=\"Source\"}"
    }
   ]
  },
  {
   "title": "Successful Source builds last 24h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(openshift_build_total{phase=\"Complete\",strategy=\"Source\"}[1d])"
    }
   ]
  },
  {
   "title": "Failed Source builds this week",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "openshift_build_total{phase=\"Failed\",strategy=\"Source\"}"
    }
   ]
  },
  {
   "title": "Failed Source builds last 24h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(openshift_build_total{phase=\"Failed\",strategy=\"Source\"}[1d])"
    }
   ]
  },
  { "title": "PIPELINE builds statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Successful Pipeline builds this week",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"}"
    }
   ]
  },
  {
   "title": "Successful Pipeline builds last 24h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"}[1d])"
    }
   ]
  },
  {
   "title": "Failed Pipeline builds this week",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "openshift_build_total{phase=\"Failed\",strategy=\"JenkinsPipeline\"}"
    }
   ]
  },
  {
   "title": "Failed Pipeline builds last 24h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(openshift_build_total{phase=\"Failed\",strategy=\"JenkinsPipeline\"}[1d])"
    }
   ]
  },
  { "title": "Deployments statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Successful Deployments this week",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"available\"}"
    }
   ]
  },
  {
   "title": "Successful Deployments last 24h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"available\"}[1d])"
    }
   ]
  },
  {
   "title": "Failed Deployments this week",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"failed\"}"
    }
   ]
  },
  {
   "title": "Failed Deployments last 24h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"failed\"}[1d])"
    }
   ]
  },
  {
   "title": "Successful pipeline builds per day of the week",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Monday",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"} and (day_of_week(timestamp(openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"})) == 1)"
    }
   ]
  },
  {
   "title": "Tuesday",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 16 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"} and (day_of_week(timestamp(openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"})) == 2)"
    }
   ]
  },
  {
   "title": "Wednesday",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"} and (day_of_week(timestamp(openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"})) == 3)"
    }
   ]
  },
  {
   "title": "Thursday",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"} and (day_of_week(timestamp(openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"})) == 4)"
    }
   ]
  },
  {
   "title": "Friday",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 16 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"} and (day_of_week(timestamp(openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"})) == 5)"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total number of completed vs failed Pipeline builds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"}"
    },
    {
     "expr": "openshift_build_total{phase=\"Failed\",strategy=\"JenkinsPipeline\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"} and (day_of_week(timestamp(openshift_build_total{phase=\"Complete\",strategy=\"JenkinsPipeline\"})) == 1)"
    }
   ]
  }
 ]
}