{
 "title": "k8s / Custom / DevOps - Kibana based",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Successful builds by Namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.namespace_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(kubernetes.container_name:sti-build) AND (message:\"Push successful\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failed builds by Namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.namespace_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(kubernetes.container_name:sti-build) AND (message:\"build error\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Successfully completed pipelines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.namespace_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(message:pipeline) AND (message:completed) AND (message: SUCCESS)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failed pipelines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.namespace_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(message:pipeline) AND (message:completed) AND (message: ABORTED)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Successful vs failed builds during period of time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(kubernetes.container_name:sti-build) AND (message:\"Push successful\")",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(kubernetes.container_name:sti-build) AND (message:\"build error\")",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}