{
 "title": "k8s / Custom / Latency",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Server Load over 15 Minutes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Replicas Available",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available) / sum(kube_deployment_status_replicas)"
    }
   ]
  },
  {
   "title": "Replicaset Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "replicationmanager_queue_latency",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "Replicas Available",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_ready) / sum(kube_statefulset_status_replicas)"
    }
   ]
  },
  {
   "title": "Statefulset Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "statefulset_queue_latency", "legendFormat": "quantile: {{quantile}}" }
   ]
  },
  {
   "title": "Replicas Available",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 19 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_current_number_scheduled) / sum(kube_daemonset_status_desired_number_scheduled)"
    }
   ]
  },
  {
   "title": "Daemonset Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "daemonset_queue_latency", "legendFormat": "quantile: {{quantile}}" }
   ]
  },
  {
   "title": "Replicas Available",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 25 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_replicaset_status_ready_replicas) / sum(kube_replicaset_status_replicas)"
    }
   ]
  },
  {
   "title": "Deployment Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "deployment_queue_latency", "legendFormat": "quantile: {{quantile}}" }
   ]
  }
 ]
}