apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: grafana-{{ grafana_name }}
    grafana-custom: {{ grafana_name }}    
  name: grafana-{{ grafana_name }}
  namespace: openshift-monitoring
spec:
  port:
    targetPort: https
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: grafana-{{ grafana_name }}
    weight: 100
  wildcardPolicy: None

