apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: grafana-{{ grafana_name }}-tls
  labels:
    app: grafana-{{ grafana_name }}
    grafana-custom: {{ grafana_name }}    
  name: grafana-{{ grafana_name }}
  namespace: openshift-monitoring
spec:
  ports:
  - name: https
    port: 3000
    protocol: TCP
    targetPort: https
  selector:
    app: grafana-{{ grafana_name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

